<?php

namespace Obs\FormationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getArticleAvant($date)
	{
		/*$query = "SELECT a FROM ObsFormationBundle:Article a WHERE a.datePost < :date";
		return $this->getEntityManager()
			->createQuery($query)
			->setParameter("date", $date)
			->getResult();*/
		$qb = $this->createQueryBuilder('a');
		
		return $qb->where("a.datePost < :date")
			->setParameter('date', $date)
			->getQuery()->getResult();
	}
	
	public function getArticles($nbParPage, $page)
	{
		$query = $this 	->createQueryBuilder('a')
						->orderBy('a.datePost', 'DESC')
						->getQuery();
		
		$query 	->setFirstResult(($page - 1) * $nbParPage)
				->setMaxResults($nbParPage);
		
		return new Paginator($query);
	}
}
